color_index – FACE
color_index Function
12 statements
Source File
private elemental function color_index(color)
Return the array-index corresponding to the queried color.
Note
Because Foreground and backround colors lists share the same name, no matter what array is used to find the color index. Thus, the foreground array is used.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: color
Color definition.
Return Value integer(kind=int32)
Index into the colors arrays.
Called by
Contents
Source Code
color_index
Source Code
   elemental function color_index(color)
   !< Return the array-index corresponding to the queried color.
   !<
   !< @note Because Foreground and backround colors lists share the same name, no matter what array is used to find the color index.
   !< Thus, the foreground array is used.
   character(len=*), intent(in) :: color       !< Color definition.
   integer(int32)               :: color_index !< Index into the colors arrays.
   integer(int32)               :: c           !< Counter.
   color_index = 0
   do c=1, size(COLORS_FG, dim=2)
      if (trim(COLORS_FG(1, c))==trim(adjustl(color))) then
         color_index = c
         exit
      endif
   enddo
   endfunction color_index
Call graph
colorize_ascii calls color_index
colorize_ucs4 calls color_index
colorize_default calls color_index
colorize calls colorize_default
colors_samples calls colorize
face_test_styles calls colorize
styles_samples calls colorize
face_test_colors calls colorize
face_test_basic calls colors_samples, styles_samples