colors_samples – FACE
colors_samples Subroutine
11 statements
Source File
public subroutine colors_samples()
Print to standard output all colors samples.
Arguments
None
Calls
Called By
Source Code
colors_samples
Source Code
  subroutine colors_samples()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Print to standard output all colors samples.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(int32) :: c !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print '(A)', colorize('Foreground colors samples', color_fg='red_intense')
  do c=1, size(COLORS_FG, dim=2)
    print '(A)', '  colorize("'//COLORS_FG(1, c)//'", color_fg="'//COLORS_FG(1, c)//'") => '//&
      colorize(COLORS_FG(1, c), color_fg=COLORS_FG(1, c))//&
      ' code: '//colorize(trim(COLORS_FG(2, c)), color_fg=COLORS_FG(1, c), style='inverse_on')
  enddo
  print '(A)', colorize('Background colors samples', color_fg='red_intense')
  do c=1, size(COLORS_BG, dim=2)
    print '(A)', '  colorize("'//COLORS_BG(1, c)//'", color_bg="'//COLORS_BG(1, c)//'") => '//&
      colorize(COLORS_BG(1, c), color_bg=COLORS_BG(1, c))//&
      ' code: '//colorize(trim(COLORS_BG(2, c)), color_bg=COLORS_BG(1, c), style='inverse_on')
  enddo
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine colors_samples
All Procedures
color_index colorize colors_samples style_index styles_samples upper
Call graph
colors_samples calls colorize
colorize calls upper, color_index, style_index
face_test_basic calls colors_samples