styles_samples – FACE
styles_samples Subroutine
7 statements
Source File
public subroutine styles_samples()
Print to standard output all styles samples.
Arguments
None
Calls
Called By
Source Code
styles_samples
Source Code
  subroutine styles_samples()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Print to standard output all styles samples.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(int32) :: s !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print '(A)', colorize('Styles samples', color_fg='red_intense')
  do s=1, size(STYLES, dim=2)
    print '(A)', '  colorize("'//STYLES(1, s)//'", style="'//STYLES(1, s)//'") => '//&
      colorize(STYLES(1, s), style=STYLES(1, s))//&
      ' code: '//colorize(trim(STYLES(2, s)), color_fg='magenta', style='inverse_on')
  enddo
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine styles_samples
All Procedures
color_index colorize colors_samples style_index styles_samples upper
Call graph
styles_samples calls colorize
colorize calls color_index, upper, style_index
face_test_basic calls styles_samples