upper – FACE
upper Function
11 statements
Source File
private elemental function upper(string)
Return a string with all uppercase characters.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Input string.
Return Value character(len=len(string))
Upper case string.
Called By
Source Code
upper
Source Code
  elemental function upper(string)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Return a string with all uppercase characters.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(len=*), intent(in) :: string !< Input string.
  character(len=len(string))   :: upper  !< Upper case string.
  integer                      :: n1     !< Characters counter.
  integer                      :: n2     !< Characters counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  upper = string
  do n1=1, len(string)
    n2 = index(LOWER_ALPHABET, string(n1:n1))
    if (n2>0) upper(n1:n1) = UPPER_ALPHABET(n2:n2)
  enddo
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction upper
All Procedures
color_index colorize colors_samples style_index styles_samples upper
Call graph
colorize calls upper
face_test_colors calls colorize
face_test_styles calls colorize
colors_samples calls colorize
styles_samples calls colorize
face_test_basic calls colors_samples, styles_samples