face_test_basic – FACE
face_test_basic Program
6 statements
Source File
Uses:
face
FACE test.
Calls
Source Code
face_test_basic
Source Code
program face_test_basic
!-----------------------------------------------------------------------------------------------------------------------------------
!< FACE test.
!-----------------------------------------------------------------------------------------------------------------------------------
use face
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
call colors_samples
call styles_samples
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram face_test_basic
All Programs
face_test_basic face_test_colors face_test_styles
Call graph
face_test_basic calls colors_samples, styles_samples
colors_samples calls colorize
styles_samples calls colorize
colorize calls upper, color_index, style_index